# Generated by Django 3.2 on 2024-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'dease',
                'verbose_name_plural': 'deases',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=16, verbose_name='identification_number'),
        ),
    ]
