# Generated by Django 4.1.5 on 2023-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_identification_insurance_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='province',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Super User'), ('STAFF', 'Staff User'), ('UMUJYANAMA', 'Umujyana')], default='UMUJYANAMA', max_length=50, verbose_name='user type'),
        ),
    ]
