# Generated by Django 3.2 on 2023-09-05 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=13)),
                ('birth_date', models.DateTimeField()),
                ('give_birth', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_clinic', to=settings.AUTH_USER_MODEL)),
                ('vigirant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vigitant_pregnancy', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregant_village', to='accounts.village')),
            ],
            options={
                'verbose_name': 'Pregnancy',
                'verbose_name_plural': 'Pregnancies',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='BirthChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('birth_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_clinic', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_family', to='home.household')),
                ('vigirant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vigitant_birth', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_village', to='accounts.village')),
            ],
            options={
                'verbose_name': 'Birth Child',
                'verbose_name_plural': 'Birth Children',
                'ordering': ('created_on',),
            },
        ),
    ]
