# Generated by Django 4.1.5 on 2023-02-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_district_province_sector_remove_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('insurance_name', models.CharField(choices=[('RSSB', 'RSSB'), ('RAMA', 'RAMA')], max_length=50)),
                ('insurance_number', models.CharField(max_length=200)),
                ('sickness', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_village', to='accounts.village')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umujyanama_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Malnutrition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_full_name', models.CharField(max_length=250)),
                ('has_malnutrition', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_malnutrition', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umujyanama_malnutrition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child  Malnutrition',
                'verbose_name_plural': 'Children  Malnutrition',
                'ordering': ('child_full_name',),
            },
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_full_name', models.CharField(max_length=250)),
                ('father_id_no', models.CharField(max_length=16, verbose_name='father_identification_number')),
                ('mother_full_name', models.CharField(max_length=250)),
                ('mother_id_no', models.CharField(max_length=16, verbose_name='mother_identification_number')),
                ('number_child', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_village', to='accounts.village')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umujyanama_family', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Hold',
                'verbose_name_plural': 'House Hold',
                'ordering': ('father_full_name',),
            },
        ),
        migrations.CreateModel(
            name='Contraception',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contraception', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umujyanama_contraception', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contraception',
                'verbose_name_plural': 'Contraception',
                'ordering': ('family',),
            },
        ),
    ]
