# Generated by Django 4.1.5 on 2023-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_name',
            field=models.CharField(max_length=50),
        ),
    ]
