# Generated by Django 4.1.5 on 2023-02-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patient_insurance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraception',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_contraception', to='home.household'),
        ),
    ]
