# Generated by Django 3.2 on 2023-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookingmedical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmedical',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
    ]
